trigger:
- master # or the name of your main branch
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
# Checkout the repository
- checkout: self
  fetchDepth: 0

# Prepare Analysis Configuration task
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'sq20254'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'minimal-python'

# Add your build task(s) here

# Run Code Analysis task
- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

# Publish Quality Gate Result task
- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'